name: script_env
channels:
  - defaults
dependencies:
  - pip=23.3
  - python=3.10.12
  - pip:
      - cython==3.0.5
      - h5py==3.9.0
      - imgaug==0.4.0
      - ipython==7.34.0
      - ipython-genutils==0.2.0
      - ipython-sql==0.5.0
      - keras==2.14.0
      - matplotlib==3.7.1
      - numpy==1.23.5
      - opencv-contrib-python==4.8.0.76
      - opencv-python==4.8.0.76
      - pillow==9.4.0
      - scikit-image
      - scipy
      - tensorboard==2.14.1
      - tensorflow==2.14.0
      - bs4==0.0.2
      - lxml==5.2.2
      - ultralytics==8.2.41
      - kraken==5.2.5
      - click
      - typing
      - dill==0.3.8
